name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    name: Lint and Format Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: "latest"

    - name: Install dependencies with Bun
      run: bun i

    - name: Lint code with ESLint
      run: bunx eslint --ext .ts,.js ./src

    - name: Check formatting with Prettier
      run: bunx prettier --check --write "./src/**/*.{ts,js,json,md}"
